<button type="submit" class =" button button-primary"><a href="<?= $requestUrl ?>/user/register">créer un compte</a></button>

<h2><i class="fas fa-lock"></i>Se connecter avec un compte utilisateur</h2>
<form method="Post" class="generic-form" action="">
	<fieldset>
		<legend>informations d'authanticites</legend>
		<ul>
			<li>
				<label for="email">Email :</label>
				<input type="email" name="Email" id="email">
			</li>

			<li>
				<label for="pasword">Mot de pass :</label>
				<input type="password" name="Password" id="pasword">
			</li>
		</ul>
	</fieldset>
	
	<button  type="submit" class=" button button-primary">Connexion</button>
	<button  type="submit" class=" button button-cancel">Annuler</button>
		
</form>
