

<button type="submit" class="button button-primary"><a href="<?= $requestUrl ?>/user/register">créer un compte</a></button>

<h2><i class="fas fa-user"></i>Creation d'un compte client</h2>

<form method="POST" class="generic-form" >
	<fieldset>
		<legend><i class="fas fa-address-book"></i>identité et cordonnées</legend>
		<ul>
			<li>
				<label  for="name">Nom :</label>
				<input type="text" name="FirstName" id="name" value ="<?=$formFields['FirstName'] ?>">
			</li>

			<li>
				<label for="prenom">Prenom :</label>
				<input type="text" name="LastName" id="prenom" value="<?=$formFields['LastName'] ?>">
			</li>

			<li>
				<label for="BirthDate">Date de naissance :</label>
				<input type="date" name="BirthDate" id="BirthDate" value="<?=$formFields['BirthDate'] ?>">
			</li>

			<li>
				<label for="Adress">Adresse :</label>
				<textarea class="textarea" name="Adress" id="Adress" value="<?=$formFields['Adress'] ?>"></textarea>
			</li>

			<li>
				<label for="City">Ville :</label>
				<input type="text" name="City" id="City" value="<?=$formFields['City'] ?>">
			</li>

			<li>
				<label for="ZipCode">Code Postale :</label>
				<input type="text" name="ZipCode" id="ZipCode" class="zip-code" value="<?=$formFields['ZipCode'] ?>">
			</li>

			<li>
				<label for="Country">Pays :</label>
				<input type="text" name="Country" id="Country">
			</li>

			<li>
				<label for="Phone">Téléphone :</label>
				<input type="phone" name="Phone" id="Phone" class="phone" value="<?=$formFields['Phone'] ?>">
			</li>
		</ul>
	</fieldset>

	<fieldset>
		<legend><i class="fas fa-lock"></i>informations d'authanticites</legend>
		<ul>
			<li>
				<label for="email">Email :</label>
				<input type="email" name="Email" id="email" >
			</li>

			<li>
				<label for="password">Mot de pass :</label>
				<input type="password" name="Password" id="password" >
			</li>
		</ul>

	</fieldset>

	<button  type="submit"  name="submit" class="button button-primary">Créer le compte</button>
	<button  type="submit" class="button button-cancel">Annuler</button>
	
</form>

<?php 
	if(isset($erreurs) && count($erreurs) > 0){
		foreach($erreurs as $erreur) {
			echo '<h3>'.$erreur.' </h3>';
		}
	}
?>