		

<button type="submit" class ="button  button-primary "><a href="<?= $requestUrl ?>/">Meal</a></button>

<button type="submit" class ="button  button-primary "><a href="<?= $requestUrl ?>/Booking">Réserver</a></button>

<button type="submit" class ="button  button-primary "><a href="<?= $requestUrl ?>/Commande">Commander</a></button>

<button type="submit" class ="button  button-primary "><a href="<?= $requestUrl ?>/LoginOut">Déconnexion</a></button>

<h2>Payment de la commande</h2>
<form method="POST"class="generic-form" >
    <fieldset>
		<legend>Recapitulatif de la commande</legend>
		  <table class="generic-table">
                <tbody>
                    <tr>
                        <th>Nom</th>
                        <th>Quanttié</th>
                        <th>Prix Unitaire</th>
                        <th>Prix Total</th> 
                     </tr>

                     <?php  foreach($paniers as $mil) : ?>
                
                     <tr> 
                        <td><?= $mil['name']; ?></td>
                        <td><?= $mil['amount']; ?></td> 
                                                  
                        <td><?= $mil['price']; ?> €</td>
                        <td><?= $mil['price']*$mil['amount']; ?> €</td>     
                    </tr>          
                        
                    <?php endforeach; ?>
                </tbody>
            </table>
    </fieldset>
</form>